[package]
name = "amai"
version = "0.0.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
colored = "3.0.0"
num_enum = "0.7.5"
phf = { version = "0.13.1", features = ["macros"] }
strum_macros = "0.27.2"
